apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: msgctf
---
apiVersion: v1
kind: Namespace
metadata:
  name: challenge
  labels:
    app.kubernetes.io/part-of: msgctf
