name: DevSecOps Sample

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  challenge-deployment:
    uses: ./.github/workflows/challenge-deployment.yml
